<?php
// Auto-generated by install.php once setup is complete.
if (!defined('DB_HOST')) define('DB_HOST', 'localhost');
if (!defined('DB_NAME')) define('DB_NAME', 'mzsmartlife');
if (!defined('DB_USER')) define('DB_USER', 'root');
if (!defined('DB_PASS')) define('DB_PASS', '');
if (!defined('BASE_URL')) define('BASE_URL', 'http://localhost');
if (!defined('APP_INSTALLED')) define('APP_INSTALLED', false);
